name: CI
on:
  push:
  public:
  pull_request:
  release:
    types: [published]

env:
  JAVA_VERSION: '21'

jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
      - name: 'Get this repo'
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.GRADLE_CACHE}}
      - name: 'Run checks'
        run: |
          ./gradlew build --no-daemon
          ./gradlew ktlintCheck --no-daemon

      - name: 'Cleanup'
        run: |
          ./gradlew clean --no-daemon
      - name: 'Archive this artifact'
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./
          retention-days: 30
