name: CI
on:
  push:
  public:
  pull_request:
  release:
    types: [published]

env:
  GRADLE_CACHE: 'gradle'
  JAVA: '17.0.6'

jobs:
  check:
    runs-on: ubuntu-latest
    steps: 
      - name: 'Get this repo'
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA }}
          cache: ${{ env.GRADLE_CACHE}}
      - name: 'Run checks'
        run: |
          ./gradlew build --no-daemon
          ./gradlew ktlintCheck --no-daemon

      - name: 'Clean after'
        run: |
          ./gradlew clean --no-daemon
      - name: 'Archive this artifact'
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./
          retention-days: 30
